---

- name: Making filesystem on device
  filesystem:
    dev: '{{ device }}'
    fstype: btrfs
    force: yes

- name: Mounting new file system
  mount:
    path: '{{ mount }}'
    src: '{{ device }}'
    fstype: btrfs
    state: mounted

- name: Setting permission for mounted partition
  file:
    path: '{{ mount }}'
    state: directory
    recurse: yes
    mode: '0777'
    owner: 'root'
    group: 'root'