---
- hosts: Benny
  serial: 1
  vars:

    mount_point: '/mnt/ext4'

    benchmark_user: benny

  tasks:

    - name: Unmount partition
      mount:
        path: '{{ mount_point }}'
        state: unmounted
      become: yes