---
- hosts: Benny
  serial: 1
  vars:

    mount_point: '/mnt/btrfs'

  tasks:

    - name: Stop docker
      systemd:
        name: docker.service
        state: stopped
      become: yes

    - name: Unmount partition
      mount:
        path: '{{ mount_point }}'
        state: unmounted
      become: yes