---
- hosts: Benny
  serial: 1
  vars:

    mount_point: '/mnt/btrfs'

    benchmark_user: benny

  tasks:

    - name: Reset podman
      command:
        cmd: podman system reset --force
      become: yes
      become_user: '{{ benchmark_user }}'

    - name: Unmount partition
      mount:
        path: '{{ mount_point }}'
        state: unmounted
      become: yes