---
- hosts: Benny
  serial: 1
  vars:

    zpool: zpool-podman

    benchmark_user: benny

  tasks:

    - name: Reset podman
      command:
        cmd: podman system reset --force
      become: yes
      become_user: '{{ benchmark_user }}'

    - name: Destroy zfs pool
      command:
        cmd: 'zpool destroy -f {{ zpool }}'
      become: yes