---
- hosts: Benny
  serial: 1
  vars:

    benchmark_repo_url: git@github.com:geverartsdev/LEPL2990-Benchmark-tool.git
    benchmark_path: /opt/container-benchmark

    benchmark_user: 'benny'
    benchmark_group: 'benny'

    tarball_path: ~/Downloads/edvgui

  tasks:

    - name: Create benchmark group
      group:
        name: '{{ benchmark_group }}'
        state: present
      become: yes

    - name: Create benchmark user
      user:
        name: '{{ benchmark_user }}'
        state: present
        group: '{{ benchmark_group }}'
      become: yes

    - name: Create benchmark user home directory
      file:
        path: '/home/{{ benchmark_user }}'
        owner: '{{ benchmark_user }}'
        group: '{{ benchmark_group }}'
        state: directory
      when: benchmark_user != 'root'
      become: yes

    - name: Install dependencies
      apt:
        name: '{{ item }}'
        state: present
        update-cache: yes
      loop: [ 'python3-pip', 'python3-dev', 'libcurl4-openssl-dev', 'libssl-dev']
      become: yes

    - name: Create benchmark directory
      file:
        path: '{{ benchmark_path }}'
        owner: '{{ ansible_user_uid }}'
        group: '{{ ansible_user_gid }}'
        state: directory
        recursive: yes
      become: yes

    - name: Retrieve latest benchmark source from repo
      git:
        repo: '{{ benchmark_repo_url }}'
        version: master
        dest: '{{ benchmark_path }}'
        accept_hostkey: yes
        force: yes
      become: no  # Can not become any other user as I am using a private key from my controller

    - name: Give ownership to benchmark user
      file:
        path: '{{ benchmark_path }}'
        owner: '{{ benchmark_user }}'
        group: '{{ benchmark_group }}'
        recurse: yes
        state: directory
      become: yes

    - name: Install pip dependencies
      pip:
        name: pycurl
        executable: pip3
      become: yes

    - name: Making sure that tarball folder exists for benchmark user
      file:
        path: '/home/{{ benchmark_user }}/Downloads/edvgui'
        owner: '{{ benchmark_user }}'
        group: '{{ benchmark_user }}'
        state: directory
      become: yes

    - name: Copying images tarball, this can take some time
      copy:
        src: '{{ tarball_path }}/{{ item }}.tar.gz'
        dest: '/home/{{ benchmark_user }}/Downloads/edvgui/{{ item }}.tar.gz'
        owner: '{{ benchmark_user }}'
        group: '{{ benchmark_user }}'
      become: yes
      loop: ['alpine-hello-world', 'alpine-http-server', 'alpine-ping',
             'alpine-db-read-xs', 'alpine-db-read-sm', 'alpine-db-read-md', 'alpine-db-read-lg', 'alpine-db-read-xl',
             'alpine-db-write-xs', 'alpine-db-write-sm', 'alpine-db-write-md', 'alpine-db-write-lg', 'alpine-db-write-xl',
             'alpine-io-read-xs', 'alpine-io-read-sm', 'alpine-io-read-md', 'alpine-io-read-lg', 'alpine-io-read-xl',
             'alpine-io-write-xs', 'alpine-io-write-sm', 'alpine-io-write-md', 'alpine-io-write-lg', 'alpine-io-write-xl']