---

- name: Install required dependency
  apt:
    name: curl
    state: latest
    update_cache: yes

- name: Check ubuntu version id
  command: /usr/bin/lsb_release -rs
  register: version_id

- name: Add Podman Release apt key
  apt_key:
    url: 'https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_{{ version_id.stdout }}/Release.key'
    state: present

- name: Add Podman repository
  apt_repository:
    repo: 'deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_{{ version_id.stdout }} /'
    filename: download_opensuse_org_libcontainers
    state: present

- name: Install podman
  apt:
    name: podman
    state: latest
    update_cache: yes

- name: Ensure path exists
  file:
    path: '/home/{{ benchmark_user }}/.config/containers/'
    state: directory

- name: Apply libpod configuration
  template:
    src: libpod.conf.j2
    dest: '/home/{{ benchmark_user }}/.config/containers/libpod.conf'
    owner: '{{ benchmark_user }}'
    group: '{{ benchmark_group }}'
    mode: '0644'

- name: Apply storage configuration
  template:
    src: storage.conf.j2
    dest: '/home/{{ benchmark_user }}/.config/containers/storage.conf'
    owner: '{{ benchmark_user }}'
    group: '{{ benchmark_group }}'
    mode: '0644'
  notify:
    - clean up storage