---

- name: Create benchmark group
  group:
    name: '{{ group }}'
    state: present

- name: Create benchmark user
  user:
    name: '{{ user }}'
    state: present
    group: '{{ group }}'

- name: Create benchmark user home directory
  file:
    path: '/home/{{ user }}'
    owner: '{{ user }}'
    group: '{{ group }}'
    state: directory
  when: user != 'root'