---

- name: Install dependency
  apt:
    name: libyajl2
    state: latest
    update_cache: yes

- name: Download crun v0.13 from github
  get_url:
    url: https://github.com/containers/crun/releases/download/0.13/crun-0.13-static-x86_64
    dest: /usr/bin/crun
    mode: '0755'
    owner: 'root'
    group: 'root'