---

- name: Install lxd
  apt:
    name: lxd
    state: latest
    update_cache: yes

- name: Generating preseed
  template:
    src: preseed.yaml.j2
    dest: /tmp/lxd-preseed.yaml

- name: Initialising lxd
  shell: cat /tmp/lxd-preseed.yaml | lxd init --preseed

- name: Add benchmark user to lxd group
  user:
    name: '{{ benchmark_user }}'
    groups: lxd
    append: yes