---
- hosts: Benny
  serial: 1
  vars:

    device: /dev/sdb1
    
  roles:

    - role: common
      vars:
        user: '{{ benchmark_user }}'
        group: '{{ benchmark_group }}'
      become: yes

    - role: install-kata
      become: yes

    - role: create-ext4
      vars:
        device: '{{ device }}'
        mount: /mnt/ext4
      become: yes
  
    - role: install-docker
      vars:
        docker_version: 'latest'
        user: '{{ benchmark_user }}'
        group: '{{ benchmark_group }}'
        data_root: /mnt/ext4/docker
        storage_driver: aufs
        default_runtime: kata-runtime
        runtimes:
          kata-runtime:
            path: /usr/bin/kata-runtime
      become: yes