---
- hosts: Benny
  serial: 1
    
  roles:

    - role: common
      become: yes

    - role: install-runc
      become: yes

    - role: create-zfs
      vars:
        device: /dev/sdb1
        mount: /mnt/zfs
        zpool: zpool-docker
      become: yes
  
    - role: install-docker
      vars:
        docker_version: 'latest'
        data_root: /mnt/zfs/docker
        storage_driver: zfs
      become: yes