---
- hosts: Benny
  serial: 1
    
  roles:

    - role: common
      become: yes

    - role: install-runc
      become: yes

    - role: create-btrfs
      vars:
        device: /dev/sdb1
        mount: /mnt/btrfs
      become: yes
  
    - role: install-docker
      vars:
        docker_version: 'latest'
        data_root: /mnt/btrfs/docker
        storage_driver: btrfs
      become: yes