---
- hosts: Benny
  serial: 1
  vars:

    device: /dev/sdb1
    
  roles:

    - role: common
      become: yes

    - role: install-runc
      become: yes

    - role: create-ext4
      vars:
        device: '{{ device }}'
        mount: /mnt/ext4
      become: yes
  
    - role: install-docker
      vars:
        docker_version: 'latest'
        data_root: /mnt/ext4/docker
        storage_driver: aufs
      become: yes