---
- hosts: Benny
  serial: 1
  vars:

    lvm_device: /dev/sdb1
    device: /dev/sdb2

    benchmark_user: benny
    benchmark_group: benny

  roles:

    - role: common
      vars:
        user: '{{ benchmark_user }}'
        group: '{{ benchmark_group }}'
      become: yes

    - role: install-crun
      become: yes

    - role: create-ext4
      vars:
        device: '{{ ext_device }}'
        mount: /mnt/ext4
      become: yes
  
    - role: install-docker
      vars:
        docker_version: 18.06.3~ce~3-0~ubuntu
        user: '{{ benchmark_user }}'
        group: '{{ benchmark_group }}'
        data_root: /mnt/ext4/docker
        storage_driver: devicemapper
        storage_opts: [
          "dm.directlvm_device={{ lvm_device }}",
          "dm.thinp_percent=95",
          "dm.thinp_metapercent=1",
          "dm.thinp_autoextend_threshold=80",
          "dm.thinp_autoextend_percent=20",
          "dm.directlvm_device_force=true"
        ]
        default_runtime: crun
        runtimes:
          crun:
            path: /usr/bin/crun
      become: yes