---
- hosts: Benny
  serial: 1
    
  roles:

    - role: common
      become: yes

    - role: create-zfs
      vars:
        device: /dev/sdb1
        mount: /mnt/zfs
        zpool: zpool-lxd
      become: yes
  
    - role: install-lxd
      vars:
        storage_driver: zfs
        storage_path: zpool-lxd
      become: yes
      become_method: sudo