---
- hosts: Benny
  serial: 1
  vars:

    device: /dev/sdb1

    benchmark_user: benny
    benchmark_group: benny
    
  roles:

    - role: common
      vars:
        user: '{{ benchmark_user }}'
        group: '{{ benchmark_group }}'
      become: yes

    - role: create-btrfs
      vars:
        device: '{{ device }}'
        mount: /mnt/btrfs
      become: yes
  
    - role: install-lxd
      vars:
        user: '{{ benchmark_user }}'
        group: '{{ benchmark_group }}'
        storage_driver: btrfs
        storage_path: /mnt/btrfs/pool1
      become: yes
      become_method: sudo