---
- hosts: Benny
  serial: 1
    
  roles:

    - role: common
      become: yes
  
    - role: install-lxd
      vars:
        storage_driver: dir
        storage_path: /tmp/pool1
      become: yes
      become_method: sudo