---
- hosts: Benny
  serial: 1
    
  roles:

    - role: common
      become: yes

    - role: create-lvm
      vars:
        device: /dev/sdb1
      become: yes
  
    - role: install-lxd
      vars:
        storage_driver: lvm
        storage_path: /dev/sdb1
      become: yes
      become_method: sudo