---
- hosts: Benny
  serial: 1
    
  roles:

    - role: common
      become: yes

    - role: create-btrfs
      vars:
        device: /dev/sdb1
        mount: /mnt/btrfs
      become: yes
  
    - role: install-lxd
      vars:
        storage_driver: btrfs
        storage_path: /mnt/btrfs/pool1
      become: yes
      become_method: sudo