---
- hosts: Benny
  serial: 1
  vars:

    device: /dev/sdb1

    benchmark_user: benny
    benchmark_group: benny
    
  roles:

    - role: common
      vars:
        user: '{{ benchmark_user }}'
        group: '{{ benchmark_group }}'
      become: yes

    - role: install-crun
      become: yes

    - role: create-ext4
      vars:
        device: '{{ device }}'
        mount: /mnt/ext4
      become: yes
  
    - role: install-podman
      vars:
        user: '{{ benchmark_user }}'
        group: '{{ benchmark_group }}'
        storage_driver: overlay
        storage_path: /mnt/ext4/podman-storage
      become: yes
