---
- hosts: Benny
  serial: 1
  vars:

    device: /dev/sdb1

    benchmark_user: benny
    benchmark_group: benny
    
  roles:

    - role: common
      vars:
        user: '{{ benchmark_user }}'
        group: '{{ benchmark_group }}'
      become: yes

    - role: install-crun
      become: yes

    - role: create-zfs
      vars:
        device: '{{ device }}'
        mount: /mnt/zfs
        zpool: zpool-podman
      become: yes
  
    - role: install-podman
      vars:
        user: '{{ benchmark_user }}'
        group: '{{ benchmark_group }}'
        storage_driver: zfs
        storage_path: /mnt/zfs/podman-storage
        zpool: zpool-podman
      become: yes
