---
- hosts: Benny
  serial: 1
    
  roles:

    - role: common
      become: yes

    - role: install-runc
      become: yes
  
    - role: install-podman
      vars:
        storage_driver: vfs
      become: yes
